### ISSUE TITLE
[Error] An error happened, please make sure your request is SFW, or use a jailbreak to bypass the filter.

### ISSUE THREAD

**Issue by MahdeenSky** [skzhengkai/free-chatgpt-api#2]
I get this error even with sfw prompts?

`{'status': False, 'error': {'message': 'An error happened, please make sure your request is SFW, or use a jailbreak to bypass the filter.', 'type': 'invalid_request_error'}}`

**Comment by BackendAdam** [comment]
Wait a little and try again

**Comment by armanhi** [comment]
Why does this happen? Any way to get around it?
